### ISSUE TITLE
Support for jQuery 1.4

### ISSUE THREAD

**Issue by mikeerickson** [kswedberg/jquery-tmbundle#3] opened 2010-03-25 18:43 UTC
Are there any immediate plans for updating this bundle so that it is compatible with the latest version of jQuery 1.4.x?

**Comment by kswedberg** [comment] 2010-03-25 18:49
yes. The grammar and the help are already updated. I just need to go through and add the new methods and the features of older methods. Let me know if there is something in particular that you'd like to see in the bundle.

thanks.

**Comment by mikeerickson** [comment] 2010-03-25 18:50
Just realized it was not updated when I tried to get documentation on $.getJSON which was added in 1.4   If you need help testing the new bundle, let me know.

**Comment by kswedberg** [comment] 2010-03-25 19:09
Ah, I see. $.getJSON was actually around before 1.4. The problem is with how TextMate determines what a word is. If you select the whole thing, you'll get the documentation, but if you just have your cursor inside "getJSON" somewhere, you won't. I'll see if I can figure out how look backwards from the word if a dot precedes it.

**Comment by mikeerickson** [comment] 2010-03-25 20:17
Actually, even if I highlight the whole word (getJSON) it doesn’t work (returns a blank page).

**Comment by kswedberg** [comment] 2010-03-25 21:24
Right -- because that's not the whole method name. ;) Highlight $.getJSON or jQuery.getJSON and you'll get the documentation.

**Comment by mikeerickson** [comment] 2010-03-26 16:07
Correct, if I highlight the whole command ($.getJSON) all works.  Why do other verbs such as 'keyup', 'fadeOut', etc work when I just highlight the command?

**Comment by kswedberg** [comment] 2010-03-26 22:13
it's because of the "." and how TextMate determines what a word is. In any case, it should be fixed now. Feel free to reopen the issue if there is still a problem.

**Closed as completed by kswedberg** 2010-03-26 22:13 UTC

**Comment by mikeerickson** [comment] 2010-03-26 22:17
Thanks for the 411, looking forward to the updated version of the .tmbundle with complete 1.4 support - thanks again!
